
export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST";

export const EVENT_LIST_SUCCESS = "EVENT_LIST_SUCCESS";

export const EVENT_LIST_FAIL = "EVENT_LIST_FAIL";

export const EVENT_LIST_TYPE_FAIL = "EVENT_LIST_TYPE_FAIL";
export const EVENT_LIST_TYPE_REQUEST = "EVENT_LIST_TYPE_REQUEST";
export const EVENT_LIST_TYPE_SUCCESS= "EVENT_LIST_TYPE_SUCCESS";

export const EVENT_IMAGE_FAIL = "EVENT_IMAGE_FAIL";
export const EVENT_IMAGE_REQUEST = "EVENT_IMAGE_REQUEST";
export const EVENT_IMAGE_SUCCESS= "EVENT_IMAGE_SUCCESS";

export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";
export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_FAIL";
