
export const EXPERTISE_LIST_REQUEST = "EXPERTISE_LIST_REQUEST";

export const EXPERTISE_LIST_SUCCESS = "EXPERTISE_LIST_SUCCESS";

export const EXPERTISE_LIST_FAIL = "EXPERTISE_LIST_FAIL";

export const EXPERTISE_LIST_TYPE_FAIL = "EXPERTISE_LIST_TYPE_FAIL";
export const EXPERTISE_LIST_TYPE_REQUEST = "EXPERTISE_LIST_TYPE_REQUEST";
export const EXPERTISE_LIST_TYPE_SUCCESS= "EXPERTISE_LIST_TYPE_SUCCESS";

export const EXPERTISE_LIST_TYPE_BYDONILAB_FAIL = "EXPERTISE_LIST_TYPE_BYDONILAB_FAIL";
export const EXPERTISE_LIST_TYPE_BYDONILAB_REQUEST = "EXPERTISE_LIST_TYPE_BYDONILAB_REQUEST";
export const EXPERTISE_LIST_TYPE_BYDONILAB_SUCCESS= "EXPERTISE_LIST_TYPE_BYDONILAB_SUCCESS";

export const EXPERTISE_DETAILS_FAIL = "EXPERTISE_DETAILS_FAIL";
export const EXPERTISE_DETAILS_REQUEST = "EXPERTISE_DETAILS_REQUEST";
export const EXPERTISE_DETAILS_SUCCESS = "EXPERTISE_DETAILS_FAIL";

export const EXPERTISE_LOGO_FAIL = "EXPERTISE_LOGO_FAIL";
export const EXPERTISE_LOGO_REQUEST = "EXPERTISE_LOGO_REQUEST";
export const EXPERTISE_LOGO_SUCCESS = "EXPERTISE_LOGO_FAIL";
