
export const DEXPERTISE_LIST_REQUEST = "DEXPERTISE_LIST_REQUEST";

export const DEXPERTISE_LIST_SUCCESS = "DEXPERTISE_LIST_SUCCESS";

export const DEXPERTISE_LIST_FAIL = "DEXPERTISE_LIST_FAIL";

export const DEXPERTISE_LIST_TYPE_FAIL = "DEXPERTISE_LIST_TYPE_FAIL";
export const DEXPERTISE_LIST_TYPE_REQUEST = "DEXPERTISE_LIST_TYPE_REQUEST";
export const DEXPERTISE_LIST_TYPE_SUCCESS= "DEXPERTISE_LIST_TYPE_SUCCESS";

export const DEXPERTISE_LIST_TYPE_BYDONILAB_FAIL = "DEXPERTISE_LIST_TYPE_BYDONILAB_FAIL";
export const DEXPERTISE_LIST_TYPE_BYDONILAB_REQUEST = "DEXPERTISE_LIST_TYPE_BYDONILAB_REQUEST";
export const DEXPERTISE_LIST_TYPE_BYDONILAB_SUCCESS= "DEXPERTISE_LIST_TYPE_BYDONILAB_SUCCESS";

export const DEXPERTISE_DETAILS_FAIL = "DEXPERTISE_DETAILS_FAIL";
export const DEXPERTISE_DETAILS_REQUEST = "DEXPERTISE_DETAILS_REQUEST";
export const DEXPERTISE_DETAILS_SUCCESS = "DEXPERTISE_DETAILS_FAIL";

export const DEXPERTISE_LOGO_FAIL = "DEXPERTISE_LOGO_FAIL";
export const DEXPERTISE_LOGO_REQUEST = "DEXPERTISE_LOGO_REQUEST";
export const DEXPERTISE_LOGO_SUCCESS = "DEXPERTISE_LOGO_FAIL";
