
export const HUB_LIST_REQUEST = "HUB_LIST_REQUEST";

export const HUB_LIST_SUCCESS = "HUB_LIST_SUCCESS";

export const HUB_LIST_FAIL = "HUB_LIST_FAIL";

export const HUB_LIST_TYPE_FAIL = "HUB_LIST_TYPE_FAIL";
export const HUB_LIST_TYPE_REQUEST = "HUB_LIST_TYPE_REQUEST";
export const HUB_LIST_TYPE_SUCCESS= "HUB_LIST_TYPE_SUCCESS";

export const HUB_IMAGE_FAIL = "HUB_IMAGE_FAIL";
export const HUB_IMAGE_REQUEST = "HUB_IMAGE_REQUEST";
export const HUB_IMAGE_SUCCESS= "HUB_IMAGE_SUCCESS";

export const HUB_DETAILS_FAIL = "HUB_DETAILS_FAIL";
export const HUB_DETAILS_REQUEST = "HUB_DETAILS_REQUEST";
export const HUB_DETAILS_SUCCESS = "HUB_DETAILS_FAIL";
