
export const PARTENAIRE_LIST_REQUEST = "PARTENAIRE_LIST_REQUEST";

export const PARTENAIRE_LIST_SUCCESS = "PARTENAIRE_LIST_SUCCESS";

export const PARTENAIRE_LIST_FAIL = "PARTENAIRE_LIST_FAIL";

export const PARTENAIRE_LIST_TYPE_FAIL = "PARTENAIRE_LIST_TYPE_FAIL";
export const PARTENAIRE_LIST_TYPE_REQUEST = "PARTENAIRE_LIST_TYPE_REQUEST";
export const PARTENAIRE_LIST_TYPE_SUCCESS= "PARTENAIRE_LIST_TYPE_SUCCESS";

export const PARTENAIRE_LIST_TYPE_BYDONILAB_FAIL = "PARTENAIRE_LIST_TYPE_BYDONILAB_FAIL";
export const PARTENAIRE_LIST_TYPE_BYDONILAB_REQUEST = "PARTENAIRE_LIST_TYPE_BYDONILAB_REQUEST";
export const PARTENAIRE_LIST_TYPE_BYDONILAB_SUCCESS= "PARTENAIRE_LIST_TYPE_BYDONILAB_SUCCESS";

export const PARTENAIRE_DETAILS_FAIL = "PARTENAIRE_DETAILS_FAIL";
export const PARTENAIRE_DETAILS_REQUEST = "PARTENAIRE_DETAILS_REQUEST";
export const PARTENAIRE_DETAILS_SUCCESS = "PARTENAIRE_DETAILS_FAIL";

export const PARTENAIRE_LOGO_FAIL = "PARTENAIRE_LOGO_FAIL";
export const PARTENAIRE_LOGO_REQUEST = "PARTENAIRE_LOGO_REQUEST";
export const PARTENAIRE_LOGO_SUCCESS = "PARTENAIRE_LOGO_FAIL";
