
export const FREXPERTISE_LIST_REQUEST = "FREXPERTISE_LIST_REQUEST";

export const FREXPERTISE_LIST_SUCCESS = "FREXPERTISE_LIST_SUCCESS";

export const FREXPERTISE_LIST_FAIL = "FREXPERTISE_LIST_FAIL";

export const FREXPERTISE_LIST_TYPE_FAIL = "FREXPERTISE_LIST_TYPE_FAIL";
export const FREXPERTISE_LIST_TYPE_REQUEST = "FREXPERTISE_LIST_TYPE_REQUEST";
export const FREXPERTISE_LIST_TYPE_SUCCESS= "FREXPERTISE_LIST_TYPE_SUCCESS";

export const FREXPERTISE_LIST_TYPE_BYDONILAB_FAIL = "FREXPERTISE_LIST_TYPE_BYDONILAB_FAIL";
export const FREXPERTISE_LIST_TYPE_BYDONILAB_REQUEST = "FREXPERTISE_LIST_TYPE_BYDONILAB_REQUEST";
export const FREXPERTISE_LIST_TYPE_BYDONILAB_SUCCESS= "FREXPERTISE_LIST_TYPE_BYDONILAB_SUCCESS";

export const FREXPERTISE_DETAILS_FAIL = "FREXPERTISE_DETAILS_FAIL";
export const FREXPERTISE_DETAILS_REQUEST = "FREXPERTISE_DETAILS_REQUEST";
export const FREXPERTISE_DETAILS_SUCCESS = "FREXPERTISE_DETAILS_FAIL";

export const FREXPERTISE_LOGO_FAIL = "FREXPERTISE_LOGO_FAIL";
export const FREXPERTISE_LOGO_REQUEST = "FREXPERTISE_LOGO_REQUEST";
export const FREXPERTISE_LOGO_SUCCESS = "FREXPERTISE_LOGO_FAIL";
