
export const POST_LIST_REQUEST = "POST_LIST_REQUEST";

export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";

export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_CATEGORIES_FAIL = "POST_CATEGORIES_FAIL";
export const POST_CATEGORIES_REQUEST = "POST_CATEGORIES_REQUEST";
export const POST_CATEGORIES_SUCCESS= "POST_CATEGORIES_SUCCESS";

export const POST_IMAGE_FAIL = "POST_IMAGE_FAIL";
export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST";
export const POST_IMAGE_SUCCESS= "POST_IMAGE_SUCCESS";
