
export const PROGRAM_LIST_REQUEST = "PROGRAM_LIST_REQUEST";

export const PROGRAM_LIST_SUCCESS = "PROGRAM_LIST_SUCCESS";

export const PROGRAM_LIST_FAIL = "PROGRAM_LIST_FAIL";

export const PROGRAM_LIST_TYPE_FAIL = "PROGRAM_LIST_TYPE_FAIL";
export const PROGRAM_LIST_TYPE_REQUEST = "PROGRAM_LIST_TYPE_REQUEST";
export const PROGRAM_LIST_TYPE_SUCCESS= "PROGRAM_LIST_TYPE_SUCCESS";

export const PROGRAM_LIST_TYPE_BYDONILAB_FAIL = "PROGRAM_LIST_TYPE_BYDONILAB_FAIL";
export const PROGRAM_LIST_TYPE_BYDONILAB_REQUEST = "PROGRAM_LIST_TYPE_BYDONILAB_REQUEST";
export const PROGRAM_LIST_TYPE_BYDONILAB_SUCCESS= "PROGRAM_LIST_TYPE_BYDONILAB_SUCCESS";

export const PROGRAM_DETAILS_FAIL = "PROGRAM_DETAILS_FAIL";
export const PROGRAM_DETAILS_REQUEST = "PROGRAM_DETAILS_REQUEST";
export const PROGRAM_DETAILS_SUCCESS = "PROGRAM_DETAILS_FAIL";

export const PROGRAM_LOGO_FAIL = "PROGRAM_LOGO_FAIL";
export const PROGRAM_LOGO_REQUEST = "PROGRAM_LOGO_REQUEST";
export const PROGRAM_LOGO_SUCCESS = "PROGRAM_LOGO_FAIL";
